crossroads/app.goodchat.hk

src/App.test.tsx, src/App.tsx, src/__tests__/integration/authentication-flow.test.tsx, src/components/AuthProvider.tsx, src/components/MainRouter/MainRouter.test.tsx, src/components/MainRouter/MainRouter.tsx, src/components/PrivateRoute.tsx, src/hooks/useAuth.ts, src/index.tsx, src/pages/Home/Home.test.tsx, src/pages/Home/Home.tsx, src/pages/Login/Login.test.tsx, src/pages/Login/Login.tsx, tsconfig.json
https://jira.crossroads.org.hk/browse/GCW-3434
It converts all relative imports to absolute imports
=> GCW-3434 Migrate from relative to absolute imports

package-lock.json, package.json
https://jira.crossroads.org.hk/browse/GCW-3437
Moves typechecking to pre-commit hook using Husky to prevent scenario where tests show up green during development, but fail in CI build.
=> GCW-3437 Move typechecking to precommit hook

src/pages/Home/Home.tsx, src/pages/Login/Login.tsx, src/test-utils/matchers/index.ts
https://jira.crossroads.org.hk/browse/GCW-3450
It modifies the queries we use in our tests to test for the presence of the page to rely more on things that are discernible to the users of our application rather than some hidden props.
=> GCW-3450 Modify page presence query

src/components/MainRouter/MainRouter.test.tsx, src/components/MainRouter/MainRouter.tsx, src/components/PrivateRoute.tsx, src/pages/Home/Home.test.tsx, src/pages/Home/__snapshots__/Home.test.tsx.snap, src/pages/Offers/Offers.test.tsx, src/pages/Offers/Offers.tsx, src/pages/Offers/__snapshots__/Offers.test.tsx.snap
https://jira.crossroads.org.hk/browse/GCW-3449
Similar to the home page, adds an offers page under the URL /offers.
=> GCW-3449 Offers page

src/components/MainRouter/MainRouter.tsx, src/components/MainTabs/MainTabs.test.tsx, src/components/MainTabs/MainTabs.tsx
https://jira.crossroads.org.hk/browse/GCW-3456
This delegates the responsibility of routing private/tabbed pages to its own component.
=> GCW-3456 Separate Router for Private/Tabbed pages

src/components/MainTabs/MainTabs.test.tsx, src/components/MainTabs/MainTabs.tsx, src/components/MainTabs/__snapshots__/MainTabs.test.tsx.snap
https://jira.crossroads.org.hk/browse/GCW-3454
Creates a bottom navbar layout with a Home tab and Offers tab which can be clicked to cycle between tabs.
=> GCW-3454 Bottom navbar with tabs

src/__tests__/integration/authentication-flow.test.tsx, src/components/MainRouter/MainRouter.test.tsx, src/components/MainRouter/MainRouter.tsx, src/pages/Authenticate/Authenticate.test.tsx, src/pages/Authenticate/Authenticate.tsx, src/pages/Login/Login.test.tsx, src/pages/Login/Login.tsx
https://jira.crossroads.org.hk/browse/GCW-3461
Creates a skeleton authentication page and updates the authentication flow to be /login --> /authenticate --> private routes instead of /login --> private routes.
=> GCW-3461 SMS PIN submission page skeleton

package-lock.json, package.json, src/mockServer.ts, src/mocks/server.ts, src/setupTests.ts
https://jira.crossroads.org.hk/browse/GCW-3478
Integrate [Mock Service Worker](https://mswjs.io/) for easier API mocking and testing
=> GCW-3478 Mock Service Worker integration

src/__tests__/integration/authentication-flow.test.tsx, src/pages/Login/Login.test.tsx, src/pages/Login/Login.tsx, src/pages/Login/test_utils.ts
https://jira.crossroads.org.hk/browse/GCW-3462
Creates the UI that allows user to input their phone number and submit the information to `auth/send_pin`.
=> GCW-3462 submit phone number to send pin endpoint

package-lock.json, package.json, src/pages/Login/test_utils.ts
https://jira.crossroads.org.hk/browse/GCW-3483
Replace verbose custom event dispatches with the abstraction provided by the Ionic Team
=> GCW-3483 Integrate ionic react test utils

src/pages/Authenticate/Authenticate.test.tsx, src/pages/Authenticate/Authenticate.tsx
https://jira.crossroads.org.hk/browse/GCW-3463
Creates the UI skeleton of the submit 2fa PIN page, with input field, placeholder, and conditional UI logic.
=> GCW-3463 submit 2FA PIN page skeleton

src/__tests__/integration/authentication-flow.test.tsx, src/hooks/useAuth/useAuth.test.tsx, src/hooks/useAuth/useAuth.ts, src/lib/services/AuthenticationService/AuthenticationService.test.ts, src/lib/services/AuthenticationService/AuthenticationService.ts, src/pages/Authenticate/Authenticate.test.tsx, src/pages/Authenticate/Authenticate.tsx
https://jira.crossroads.org.hk/browse/GCW-3486
Implements the second part of the authentication flow where user inputs their 2fa pin to authenticate.
=> GCW-3486 Submit 2FA to login

src/hooks/useAuth/useAuth.test.tsx, src/lib/client/client.ts, src/lib/errors.ts, src/lib/services/AuthenticationService/AuthenticationService.test.ts, src/pages/Authenticate/Authenticate.test.tsx, src/pages/Authenticate/Authenticate.tsx, src/pages/Login/Login.test.tsx, src/pages/Login/Login.tsx
https://jira.crossroads.org.hk/browse/GCW-3498
Makes the error messages shown during authentication flow more specific rather than a generic "something went wrong".
=> GCW-3498 Make authentication flow error messages more specific

package-lock.json, src/hooks/useAsync.ts, src/hooks/useSafeSetState.ts, src/lib/errors.ts, src/pages/Authenticate/Authenticate.test.tsx, src/pages/Authenticate/Authenticate.tsx, src/pages/Login/Login.test.tsx, src/pages/Login/Login.tsx
https://jira.crossroads.org.hk/browse/GCW-3503
Creates a `useAsync` hook that encapsulates loading, error, data states, and provides an executor to execute the asynchronous callback.
=> GCW-3503 useAsync hook

.env, package-lock.json, package.json, src/App.tsx, src/lib/HasuraClient.ts, src/lib/services/AuthenticationService/AuthenticationService.ts
https://jira.crossroads.org.hk/browse/GCW-3546
Creates a basic client to communicate with Hasura and make graphQL requests. Makes use of Apollo GraphQL
=> GCW-3546 Basic Hasura client

src/lib/HasuraClient.ts, src/lib/services/AuthenticationService/AuthenticationService.test.ts, src/lib/services/AuthenticationService/AuthenticationService.ts, src/lib/services/AuthenticationService/types.ts, src/lib/utils.ts, src/test-utils/mocks/apiResponses.ts
https://jira.crossroads.org.hk/browse/GCW-3547
Creates the logic to refresh hasura token when receiving an unauthorized error from Hasura.
=> GCW-3547 Refresh Hasura token and retry operation on unauthorized error

src/lib/HasuraClient.ts, src/lib/utils.ts
https://jira.crossroads.org.hk/browse/GCW-3552
Corrects the incorrect terminology used to describe a `throttle` function
=> GCW-3552 Rename debounce --> throttle

.env, .env.sample, .gitignore
https://jira.crossroads.org.hk/browse/GCW-3562
Remove .env from version control and puts in its place a sample env with instructions on the handling of public and secret environment variables. Also, provides defaults for the values.
=> GCW-3562 Remove .env from version control and add .env.sample

.env.sample, src/lib/GoodChatClient/createGoodChatClient.ts, src/lib/services/AuthenticationService/AuthenticationService.ts
https://jira.crossroads.org.hk/browse/GCW-3599
Creates a GraphQL Client to interact with GoodChat
=> GCW-3599 GoodChat client

.env.sample, codegen.yml, src/App.tsx, src/__tests__/integration/authentication-flow.test.tsx
https://jira.crossroads.org.hk/browse/GCW-3600
Supporting multiple graphQL clients, including support for code generation will take some time. For now it would be better to focus on the chat functionality.
Therefore, this replaces usages of HasuraClient with GoodChat client.
=> GCW-3600 Replace usages of HasuraClient with GoodChatClient

codegen.yml, graphql.config.json
https://jira.crossroads.org.hk/browse/GCW-3602
Allow for generating types and autocompletion in `.gql` files.
=> GCW-3602 Add codegen and autocomplete support for .gql files

graphql.schema.json, src/generated/graphql.tsx, src/hooks/useMessages.ts, src/pages/Chat/Chat.test.tsx, src/pages/Chat/Chat.tsx, src/pages/Chat/markAsRead.gql, src/test-utils/factories/message.factory.ts
https://jira.crossroads.org.hk/secure/RapidBoard.jspa?rapidView=4&view=detail&selectedIssue=GCW-3673
Fires mark as read event upon visiting an individual conversation as well as every time a new messages comes in.
=> GCW-3673 Fire mark as read mutation in conversation

package-lock.json, package.json, src/components/MainRouter/MainRouter.test.tsx, src/components/MainRouter/MainRouter.tsx, src/hooks/useLayoutTrigger.ts, src/hooks/useMediator.ts, src/hooks/useMutation.ts, src/lib/GoodChatClient/createGoodChatClient.ts, src/lib/services/Mediator/Mediator.ts, src/lib/utils/async.ts, src/pages/Chat/Chat.tsx
Changes:
- 401s are propagated via the mediator service, and the router redirects to the /login page
- Scroll down the chat message list on detection of content
=> :art: ADD: 401 redirects to login
